Write stuff
urbit/sample-apps pull request #28
Opened 2017-02-27 20:06 UTC by keatondunsford

Add Project Euler 4 and 9, and add insertion sort to our example sorting library. Additionally add correct commenting format, annotating the code line-by-line. Eventually will update rest of examples to same commentary format, i.e. the same format used in new `zuse` and `jael` (a @cgyarvin  request).

2017-02-27 22:03 UTC, galenwp commented
@cgyarvin can you approve / merge when ready?

2017-02-27 22:10 UTC, cgyarvin commented
Yes, I'll review.

On Mon, Feb 27, 2017 at 2:03 PM, Galen Wolfe-Pauly <notifications@github.com
> wrote:

> @cgyarvin <https://github.com/cgyarvin> can you approve / merge when
> ready?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/urbit/examples/pull/28#issuecomment-282870930>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AALyAbnxSuCjMs1ZSPAKaaAB1fDF3dz7ks5rg0gogaJpZM4MNkFZ>
> .
>

2017-03-01 20:39 UTC, cgyarvin requested changes
It's a fun trick, but you can't actually use <> to detect palindromes!  It does work in this instance, but it's meant for printing.  It kind of gives people the wrong idea and it's not really in the spirit of the Euler problems, which are supposed to show number manipulation...

Also, the sorts and examples should be separate PRs.

2017-03-01 20:42 UTC, juped commented
I hate to be the bearer of harsh reality, but EVERYONE stringizes on that problem.

It's actually trickier in Urbit because you have to de-. it

2017-03-02 00:09 UTC, ohAitch commented
Yes, but the correct stringizing here is (pojo (jone x)) or sth

On Wed, Mar 1, 2017 at 12:42 PM, Raymond Pasco <notifications@github.com>
wrote:

> I hate to be the bearer of harsh reality, but EVERYONE stringizes on that
> problem.
>
> It's actually trickier in Urbit because you have to de-. it
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/urbit/examples/pull/28#issuecomment-283463642>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABxXhonHOk_ew7zoLnUR6d-OSchvzhCiks5rhdhMgaJpZM4MNkFZ>
> .
>

2017-03-02 00:12 UTC, cgyarvin commented
It actually works fine with the ., but only because 3-digit numbers are
being asked for.

It's not super hard to write a function that produces decimal digit `n` of
an atom...

On Wed, Mar 1, 2017 at 4:09 PM, Anton Dyudin <notifications@github.com>
wrote:

> Yes, but the correct stringizing here is (pojo (jone x)) or sth
>
> On Wed, Mar 1, 2017 at 12:42 PM, Raymond Pasco <notifications@github.com>
> wrote:
>
> > I hate to be the bearer of harsh reality, but EVERYONE stringizes on that
> > problem.
> >
> > It's actually trickier in Urbit because you have to de-. it
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/urbit/examples/pull/28#issuecomment-283463642>, or
> mute
> > the thread
> > <https://github.com/notifications/unsubscribe-
> auth/ABxXhonHOk_ew7zoLnUR6d-OSchvzhCiks5rhdhMgaJpZM4MNkFZ>
> > .
>
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/urbit/examples/pull/28#issuecomment-283513701>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AALyAcqn2lalTgSAvfpP3gemi7GeiJNhks5rhgi6gaJpZM4MNkFZ>
> .
>

2017-03-02 00:20 UTC, juped commented
It works fine on everything, but there are later problems where you have to take it into account.

If you can find a solution to this in the wild that doesn't use language-idiomatic sprintf("%d") I'll eat my hat. And I only own one hat.

2017-03-02 00:23 UTC, ohAitch commented
Does bf have language idioms?

On Wednesday, 1 March 2017, Raymond Pasco <notifications@github.com> wrote:

> It works fine on everything, but there are later problems where you have
> to take it into account.
>
> If you can find a solution to this in the wild that doesn't use
> language-idiomatic sprintf("%d") I'll eat my hat. And I only own one hat.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/urbit/examples/pull/28#issuecomment-283515643>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABxXhjfW5U00EXxQs2n9hrE8DqAM1wVqks5rhgtRgaJpZM4MNkFZ>
> .
>

2017-03-02 00:29 UTC, cgyarvin commented
I spent 4 minutes, which are 4 minutes of my life I'll never get back,
trying to find an example to make you eat your hat.  So okay, fine.

The examples and the sorts should still be separate PRs, though.

On Wed, Mar 1, 2017 at 4:20 PM, Raymond Pasco <notifications@github.com>
wrote:

> It works fine on everything, but there are later problems where you have
> to take it into account.
>
> If you can find a solution to this in the wild that doesn't use
> language-idiomatic sprintf("%d") I'll eat my hat. And I only own one hat.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/urbit/examples/pull/28#issuecomment-283515643>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AALyAZ8gIGxxSBAWzKeTVjmclzaCMxMlks5rhgtQgaJpZM4MNkFZ>
> .
>

2017-03-02 00:41 UTC, keatondunsford commented
So, don't do the (pojo (jone x))/sth thing and PR as is (with sorts separated)?

Just want to try and introduce as little new syntax/lib functions as possible as Euler 9 is still in newbie territory. If <abc> is fundamentally bad, I'd love to know why (the one-sentence summary, to not waste more of your life's minutes). My thought process was to show, "Hey, if I ever want to turn something into a tape, and do tape/list stuff on it, this is an easy way!"

2017-03-02 00:44 UTC, juped commented
Anton's deadpan jokes are so subtle, he could make Margaret Dumont out of Groucho Marx

2017-03-02 00:47 UTC, cgyarvin commented
Because the spirit of pretty-printing is one-way.  The fact that you can
parse it back feels uncontrolled and random.  I wouldn't drag JS into this
-- use (scow %ui atom) and cut off the 0i.

On Wed, Mar 1, 2017 at 4:41 PM, Keaton Dunsford <notifications@github.com>
wrote:

> So, don't do the (pojo (jone x))/sth thing and PR as is (with sorts
> separated)?
>
> Just want to try and introduce as little new syntax/lib functions as
> possible as Euler 9 is still in newbie territory. If is fundamentally bad,
> I'd love to know why (the one-sentence summary, to not waste more of your
> life's minutes). My thought process was to show, "Hey, if I ever want to
> turn something into a tape, and do tape/list stuff on it, this is an easy
> way!"
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/urbit/examples/pull/28#issuecomment-283519197>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AALyAWuv2CXIVCghlcjeVZjPTy3sXTx0ks5rhhA0gaJpZM4MNkFZ>
> .
>

2017-07-26 19:17 UTC, closed without merging